pluginManagement {
	repositories {
		// 阿里云镜像（加速）
		maven {
			name = 'Aliyun Maven'
			url = 'https://maven.aliyun.com/repository/public/'
		}
		maven {
			name = 'Aliyun Gradle'
			url = 'https://maven.aliyun.com/repository/gradle-plugin/'
		}
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		maven {
			url = "https://repository.hanbings.io/releases"
		}
		maven {
			url = "https://repository.hanbings.io/proxy"
		}
		maven {
			url = "https://repository.hanbings.io/snapshots"
		}
		gradlePluginPortal()
	}
}